FOSWIKI_ROOT?=~/foswiki/trunk/core
TARGET=\
  jquery.catselector.js \
  jquery.classifiedtopic.js \
  jquery.hierarchy.js \
  jquery.tagcloud.js \
  jquery.tagselector.js \
  jquery.tagsuggestion.js \
  renametag.js \
  styles.css

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include
