FOSWIKI_ROOT?=~/foswiki/trunk/core
TARGET=\
  jquery.catselector.js \
  jquery.tageditor.js \
  jquery.classifiedtopic.js \
  jquery.hierarchy.js \
  jquery.tagcloud.js \
  renametag.js \
  styles.css

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

clean:
	rm $(TARGET) *.gz
